packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@next/env@16.2.7'
  - '@next/eslint-plugin-next@16.2.7'
  - '@next/swc-darwin-arm64@16.2.7'
  - '@next/swc-darwin-x64@16.2.7'
  - '@next/swc-linux-arm64-gnu@16.2.7'
  - '@next/swc-linux-arm64-musl@16.2.7'
  - '@next/swc-linux-x64-gnu@16.2.7'
  - '@next/swc-linux-x64-musl@16.2.7'
  - '@next/swc-win32-arm64-msvc@16.2.7'
  - '@next/swc-win32-x64-msvc@16.2.7'
  - eslint-config-next@16.2.7
  - next@16.2.7
